# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59b13734907c0a01206b0c80a4a4f8e88eef4a5ad7a30aa4ca27644eea650252cba97c14e11e90be6b8da51494f2dae7aea36c4e6eed3aac59dd82de3b507573

test:
  secret_key_base: 356f889298493f9e868b4f9057efe11d213e19fc57d030749dc10607eb663cba715ea2ecea8fa4f0953805ec1dd23103a180dbb16b12ff7aa3094feda1924726

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
